### PR TITLE
Add try/catch block around bad index access. [#89308488] [#89348748]

### PR DESCRIPTION
**Pull request by greghe**

### CODE REVIEW

**Comment by jnhuynh** [comment]
:+1: 
 Silently catching exceptions feels wrong. Maybe we should add some log?

**Comment by greghe** [comment]
We have lots of crashlytics logs. Apparently because expandedCell no longer refers to a valid cell.

**Comment by MattFoley** [comment]
https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Exceptions/Articles/Exceptions64Bit.html

**Comment by MattFoley** [comment]
:+1:

**Comment by greghe** [comment]
looks good.

**Pull request merged**
